name: codecov
env:
    DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codecov:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests using 'xcodebuild'
      run: xcodebuild test -enableCodeCoverage YES -scheme Blitzlichtgewitter -destination 'platform=OS X'
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1.0.13
